baseURL = "http://rakan.me/"
languageCode = "en-us"
title = "Rakan"
theme = "mainroad"

paginate = "10"
sectionPagesMenu = "main"

disqusShortname = "alhneiti"
googleAnalytics = "UA-24425385-1"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = -100

#[[menu.main]]
#    name = "Programming"
#    weight = -90
#    identifier = "programming"
#    url = "/programming/"

[[menu.main]]
    name = "Emacs"
    weight = -80
    identifier = "emacs"
    url = "/emacs/"

[[menu.main]]
    name = "Projects"
    weight = -70
    identifier = "projects"
    url = "/projects"

[Author] # Used in authorbox
    name = "Rakan Alhneiti"
    bio = "Python / Go developer, passionate about Emacs and Software Development topics"
    avatar = "img/avatar.png"

[Params]
    opengraph = true # Enable OpenGraph if true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["programming", "emacs"] # alternative that shows more than one section's pages

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_twitter = "rakanalh"
    social_linkedin = "rakanalhneiti"
    social_github = "rakanalh"